# Generated by Django 3.1.1 on 2020-09-28 15:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='NA', max_length=75)),
                ('title', models.CharField(max_length=100)),
                ('Submission_type', models.CharField(choices=[('base year emissions goal', 'BASE YEAR EMISSIONS GOAL'), ('fixed-level goal', 'FIXED-LEVEL GOAL'), ('base year intensity goal', 'BASE YEAR INTENSITY GOAL'), ('baseline emissions goal', 'BASELINE EMISSIONS GOAL')], default='base year emissions goal', max_length=75)),
                ('Submission_date', models.DateField(default=datetime.date.today)),
                ('Description', models.TextField(default='NA', max_length=250)),
                ('NDC_Text', models.FileField(default='NA', max_length=254, upload_to='static/')),
                ('ref_num', models.IntegerField(default='0')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
