# Generated by Django 3.1.1 on 2020-09-23 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ndc',
            old_name='party',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='title',
        ),
        migrations.AddField(
            model_name='ndc',
            name='Country',
            field=models.CharField(default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='Description',
            field=models.TextField(default='NA', max_length=250),
        ),
        migrations.AddField(
            model_name='ndc',
            name='NDC_Text',
            field=models.FileField(default='NA', max_length=254, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='ndc',
            name='Submission_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ndc',
            name='Submission_type',
            field=models.CharField(choices=[('base year emissions goal', 'BASE YEAR EMISSIONS GOAL'), ('fixed-level goal', 'FIXED-LEVEL GOAL'), ('base year intensity goal', 'BASE YEAR INTENSITY GOAL'), ('baseline emissions goal', 'BASELINE EMISSIONS GOAL')], default='base year emissions goal', max_length=75),
        ),
        migrations.AlterField(
            model_name='ndc',
            name='ref_num',
            field=models.IntegerField(default='NA'),
        ),
    ]
