# Generated by Django 3.1.2 on 2020-10-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_cc_mitigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CC_Adaptation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_and_displacement_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('migration_and_displacement_details', models.CharField(default='NA', max_length=125)),
                ('vulnerability_agriculture_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('vulnerability_agriculture_details', models.CharField(default='NA', max_length=125)),
                ('vulnerability_water_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('vulnerability_water_details', models.CharField(default='NA', max_length=125)),
                ('vulnerability_ecosystems_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('vulnerability_ecosystems_details', models.CharField(default='NA', max_length=125)),
                ('vulnerability_health_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('vulnerability_health_details', models.CharField(default='NA', max_length=125)),
                ('vulnerability_coastal_zones_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('vulnerability_coastal_zones_details', models.CharField(default='NA', max_length=125)),
                ('costs_of_recent_climate_related_hazards_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('costs_of_recent_climate_related_hazards_details', models.CharField(default='NA', max_length=125)),
                ('costs_of_future_climate_related_hazards_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('costs_of_future_climate_related_hazards_details', models.CharField(default='NA', max_length=125)),
                ('climate_risks_extreme_weather_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('climate_risks_extreme_weather_details', models.CharField(default='NA', max_length=125)),
                ('climate_risks_floods_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('climate_risks_floods_details', models.CharField(default='NA', max_length=125)),
                ('climate_risks_droughts_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('climate_risks_droughts_details', models.CharField(default='NA', max_length=125)),
                ('climate_risks_temp_increase_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('climate_risks_temp_increase_details', models.CharField(default='NA', max_length=125)),
                ('climate_risks_sea_level_rise_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('climate_risks_sea_level_rise_details', models.CharField(default='NA', max_length=125)),
                ('priority_sectors_water_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('priority_sectors_water_details', models.CharField(default='NA', max_length=125)),
                ('priority_sectors_agriculture_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('priority_sectors_agriculture_details', models.CharField(default='NA', max_length=125)),
                ('priority_sectors_health_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('priority_sectors_health_details', models.CharField(default='NA', max_length=125)),
                ('priority_sectors_ecosystems_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('priority_sectors_ecosystems_details', models.CharField(default='NA', max_length=125)),
                ('priority_sectors_forestry_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('priority_sectors_forestry_details', models.CharField(default='NA', max_length=125)),
                ('quantified_adaptation_targets_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('quantified_adaptation_targets_details', models.CharField(default='NA', max_length=125)),
                ('costs_of_adaptation_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('costs_of_adaptation_details', models.CharField(default='NA', max_length=125)),
                ('adaptation_documents_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('adaptation_documents_details', models.CharField(default='NA', max_length=125)),
                ('co_benefits_of_adaptation_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('co_benefits_of_adaptation_details', models.CharField(default='NA', max_length=125)),
            ],
        ),
    ]
