# Generated by Django 3.1.1 on 2020-09-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200923_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ndc',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='ndc',
            old_name='Title',
            new_name='title',
        ),
    ]
