# Generated by Django 3.1.2 on 2020-10-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_cc_adaptation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fina_and_Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditionality_of_adaptation_finance_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('conditionality_of_adaptation_finance_details', models.CharField(default='NA', max_length=125)),
                ('conditionality_of_mitigation_finance_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('conditionality_of_mitigation_finance_details', models.CharField(default='NA', max_length=125)),
                ('technology_needs_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('technology_needs_details', models.CharField(default='NA', max_length=125)),
                ('conditionality_of_technology_transfer_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('conditionality_of_technology_transfer_details', models.CharField(default='NA', max_length=125)),
                ('conditionality_of_capacity_building_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('conditionality_of_capacity_building_details', models.CharField(default='NA', max_length=125)),
                ('means_of_implementation_and_fairness_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('means_of_implementation_and_fairness_details', models.CharField(default='NA', max_length=125)),
                ('climate_risk_insurance_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('climate_risk_insurance_details', models.CharField(default='NA', max_length=125)),
            ],
        ),
    ]
