# Generated by Django 3.1.2 on 2020-10-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_fina_and_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broader_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sustainable_development_goals_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('sustainable_development_goals_details', models.CharField(default='NA', max_length=125)),
                ('sustainable_development_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('sustainable_development_details', models.CharField(default='NA', max_length=125)),
                ('fossil_fuel_subsidy_reform_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('fossil_fuel_subsidy_reform_details', models.CharField(default='NA', max_length=125)),
                ('green_economy_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('green_economy_details', models.CharField(default='NA', max_length=125)),
                ('disaster_risk_reduction_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('disaster_risk_reduction_details', models.CharField(default='NA', max_length=125)),
                ('section_on_fairness_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('section_on_fairness_details', models.CharField(default='NA', max_length=125)),
                ('historical_responsibility_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('historical_responsibility_details', models.CharField(default='NA', max_length=125)),
                ('loss_and_damage_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('loss_and_damage_details', models.CharField(default='NA', max_length=125)),
                ('gender_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('gender_details', models.CharField(default='NA', max_length=125)),
                ('human_rights_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('human_rights_details', models.CharField(default='NA', max_length=125)),
                ('income_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('income_details', models.CharField(default='NA', max_length=125)),
                ('region_id', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('region_name', models.CharField(default='NA', max_length=125)),
                ('g20_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('g20_details', models.CharField(default='NA', max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Planning_Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_of_ndc_formulation_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('planning_of_ndc_formulation_details', models.CharField(default='NA', max_length=125)),
                ('stakeholder_consultation_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('stakeholder_consultation_details', models.CharField(default='NA', max_length=125)),
                ('education_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('education_details', models.CharField(default='NA', max_length=125)),
                ('aw_rais_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('aw_rais_details', models.CharField(default='NA', max_length=125)),
                ('training_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('training_details', models.CharField(default='NA', max_length=125)),
                ('info_access_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('info_access_details', models.CharField(default='NA', max_length=125)),
                ('planning_of_ndc_implementation_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('planning_of_ndc_implementation_details', models.CharField(default='NA', max_length=125)),
                ('monitoring_and_review_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('monitoring_and_review_details', models.CharField(default='NA', max_length=125)),
            ],
        ),
    ]
