# Generated by Django 3.1.2 on 2020-10-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_broader_picture_planning_process'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Broader_Picture',
        ),
        migrations.DeleteModel(
            name='CC_Adaptation',
        ),
        migrations.DeleteModel(
            name='CC_Mitigation',
        ),
        migrations.DeleteModel(
            name='Fina_and_Support',
        ),
        migrations.DeleteModel(
            name='Planning_Process',
        ),
        migrations.AddField(
            model_name='ndc',
            name='adaptation_documents_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='adaptation_documents_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='agriculture_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='agriculture_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='aw_rais_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='aw_rais_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='carbon_capture_and_storage_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='carbon_capture_and_storage_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='climate_risk_insurance_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='climate_risk_insurance_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='climate_risks_droughts_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='climate_risks_droughts_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='climate_risks_extreme_weather_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='climate_risks_extreme_weather_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='climate_risks_floods_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='climate_risks_floods_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='climate_risks_sea_level_rise_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='climate_risks_sea_level_rise_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='climate_risks_temp_increase_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='climate_risks_temp_increase_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='co_benefits_ccm_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='co_benefits_ccm_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='co_benefits_of_adaptation_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='co_benefits_of_adaptation_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='conditionality_of_adaptation_finance_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='conditionality_of_adaptation_finance_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='conditionality_of_capacity_building_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='conditionality_of_capacity_building_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='conditionality_of_mitigation_finance_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='conditionality_of_mitigation_finance_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='conditionality_of_technology_transfer_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='conditionality_of_technology_transfer_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='costs_of_adaptation_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='costs_of_adaptation_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='costs_of_ccm_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='costs_of_ccm_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='costs_of_future_climate_related_hazards_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='costs_of_future_climate_related_hazards_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='costs_of_recent_climate_related_hazards_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='costs_of_recent_climate_related_hazards_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='country_code',
            field=models.CharField(default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='country_name',
            field=models.CharField(default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='disaster_risk_reduction_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='disaster_risk_reduction_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='education_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='education_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='energy_efficiency_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='energy_efficiency_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='fossil_fuel_production_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='fossil_fuel_production_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='fossil_fuel_subsidiaries_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='fossil_fuel_subsidiaries_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='fossil_fuel_subsidy_reform_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='fossil_fuel_subsidy_reform_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='g20_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='g20_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='gender_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='gender_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='green_economy_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='green_economy_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='historical_responsibility_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='historical_responsibility_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='human_rights_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='human_rights_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='income_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='income_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='info_access_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='info_access_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='land_use_and_forestry_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='land_use_and_forestry_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='land_use_change_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='land_use_change_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='loss_and_damage_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='loss_and_damage_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='market_mechanisms_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='market_mechanisms_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='means_of_implementation_and_fairness_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='means_of_implementation_and_fairness_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='migration_and_displacement_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='migration_and_displacement_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='mitigation_documents_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='mitigation_documents_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='monitoring_and_review_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='monitoring_and_review_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='planning_of_ndc_formulation_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='planning_of_ndc_formulation_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='planning_of_ndc_implementation_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='planning_of_ndc_implementation_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='priority_sectors_agriculture_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='priority_sectors_agriculture_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='priority_sectors_ecosystems_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='priority_sectors_ecosystems_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='priority_sectors_forestry_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='priority_sectors_forestry_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='priority_sectors_health_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='priority_sectors_health_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='priority_sectors_water_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='priority_sectors_water_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='quantified_adaptation_targets_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='quantified_adaptation_targets_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='redd_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='redd_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='reducing_non_co2_gases_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='reducing_non_co2_gases_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='region_id',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='region_name',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='renewable_energy_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='renewable_energy_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='section_on_fairness_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='section_on_fairness_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='stakeholder_consultation_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='stakeholder_consultation_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='sustainable_development_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='sustainable_development_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='sustainable_development_goals_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='sustainable_development_goals_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='technology_needs_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='technology_needs_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='temp_target_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='temp_target_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='trade_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='trade_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='training_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='training_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='transport_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='transport_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='type_of_target_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='type_of_target_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='vulnerability_agriculture_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='vulnerability_agriculture_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='vulnerability_coastal_zones_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='vulnerability_coastal_zones_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='vulnerability_ecosystems_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='vulnerability_ecosystems_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='vulnerability_health_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='vulnerability_health_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='vulnerability_water_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='vulnerability_water_details',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AddField(
            model_name='ndc',
            name='waste_class',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='waste_details',
            field=models.CharField(default='NA', max_length=125),
        ),
    ]
