# Generated by Django 3.1.2 on 2020-10-14 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201014_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndc',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
