# Generated by Django 3.1.3 on 2020-11-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_ndc_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ndc_data_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='NA', max_length=75)),
                ('country_code', models.CharField(default='NA', max_length=75)),
                ('type_of_target_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('type_of_target_details', models.CharField(default='NA', max_length=125)),
                ('temp_target_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('temp_target_details', models.CharField(default='NA', max_length=125)),
                ('costs_of_ccm_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('costs_of_ccm_details', models.CharField(default='NA', max_length=125)),
                ('renewable_energy_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('renewable_energy_details', models.CharField(default='NA', max_length=125)),
                ('energy_efficiency_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('energy_efficiency_details', models.CharField(default='NA', max_length=125)),
                ('transport_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('transport_details', models.CharField(default='NA', max_length=125)),
                ('carbon_capture_and_storage_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('carbon_capture_and_storage_details', models.CharField(default='NA', max_length=125)),
                ('agriculture_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('agriculture_details', models.CharField(default='NA', max_length=125)),
                ('land_use_and_forestry_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('land_use_and_forestry_details', models.CharField(default='NA', max_length=125)),
                ('waste_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('waste_details', models.CharField(default='NA', max_length=125)),
                ('reducing_non_co2_gases_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('reducing_non_co2_gases_details', models.CharField(default='NA', max_length=125)),
                ('fossil_fuel_production_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('fossil_fuel_production_details', models.CharField(default='NA', max_length=125)),
                ('fossil_fuel_subsidiaries_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('fossil_fuel_subsidiaries_details', models.CharField(default='NA', max_length=125)),
                ('land_use_change_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('land_use_change_details', models.CharField(default='NA', max_length=125)),
                ('redd_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('redd_details', models.CharField(default='NA', max_length=125)),
                ('trade_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('trade_details', models.CharField(default='NA', max_length=125)),
                ('market_mechanisms_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('market_mechanisms_details', models.CharField(default='NA', max_length=125)),
                ('mitigation_documents_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('mitigation_documents_details', models.CharField(default='NA', max_length=125)),
                ('co_benefits_ccm_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('co_benefits_ccm_details', models.CharField(default='NA', max_length=125)),
                ('migration_and_displacement_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('migration_and_displacement_details', models.CharField(default='NA', max_length=125)),
                ('vulnerability_agriculture_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('vulnerability_agriculture_details', models.CharField(default='NA', max_length=125)),
                ('vulnerability_water_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('vulnerability_water_details', models.CharField(default='NA', max_length=125)),
                ('vulnerability_ecosystems_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('vulnerability_ecosystems_details', models.CharField(default='NA', max_length=125)),
                ('vulnerability_health_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('vulnerability_health_details', models.CharField(default='NA', max_length=125)),
                ('vulnerability_coastal_zones_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('vulnerability_coastal_zones_details', models.CharField(default='NA', max_length=125)),
                ('costs_of_recent_climate_related_hazards_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('costs_of_recent_climate_related_hazards_details', models.CharField(default='NA', max_length=125)),
                ('costs_of_future_climate_related_hazards_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('costs_of_future_climate_related_hazards_details', models.CharField(default='NA', max_length=125)),
                ('climate_risks_extreme_weather_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('climate_risks_extreme_weather_details', models.CharField(default='NA', max_length=125)),
                ('climate_risks_floods_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('climate_risks_floods_details', models.CharField(default='NA', max_length=125)),
                ('climate_risks_droughts_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('climate_risks_droughts_details', models.CharField(default='NA', max_length=125)),
                ('climate_risks_temp_increase_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('climate_risks_temp_increase_details', models.CharField(default='NA', max_length=125)),
                ('climate_risks_sea_level_rise_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('climate_risks_sea_level_rise_details', models.CharField(default='NA', max_length=125)),
                ('priority_sectors_water_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('priority_sectors_water_details', models.CharField(default='NA', max_length=125)),
                ('priority_sectors_agriculture_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('priority_sectors_agriculture_details', models.CharField(default='NA', max_length=125)),
                ('priority_sectors_health_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('priority_sectors_health_details', models.CharField(default='NA', max_length=125)),
                ('priority_sectors_ecosystems_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('priority_sectors_ecosystems_details', models.CharField(default='NA', max_length=125)),
                ('priority_sectors_forestry_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('priority_sectors_forestry_details', models.CharField(default='NA', max_length=125)),
                ('quantified_adaptation_targets_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('quantified_adaptation_targets_details', models.CharField(default='NA', max_length=125)),
                ('costs_of_adaptation_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('costs_of_adaptation_details', models.CharField(default='NA', max_length=125)),
                ('adaptation_documents_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('adaptation_documents_details', models.CharField(default='NA', max_length=125)),
                ('co_benefits_of_adaptation_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('co_benefits_of_adaptation_details', models.CharField(default='NA', max_length=125)),
                ('conditionality_of_adaptation_finance_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('conditionality_of_adaptation_finance_details', models.CharField(default='NA', max_length=125)),
                ('conditionality_of_mitigation_finance_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('conditionality_of_mitigation_finance_details', models.CharField(default='NA', max_length=125)),
                ('technology_needs_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('technology_needs_details', models.CharField(default='NA', max_length=125)),
                ('conditionality_of_technology_transfer_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('conditionality_of_technology_transfer_details', models.CharField(default='NA', max_length=125)),
                ('conditionality_of_capacity_building_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('conditionality_of_capacity_building_details', models.CharField(default='NA', max_length=125)),
                ('means_of_implementation_and_fairness_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('means_of_implementation_and_fairness_details', models.CharField(default='NA', max_length=125)),
                ('climate_risk_insurance_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('climate_risk_insurance_details', models.CharField(default='NA', max_length=125)),
                ('planning_of_ndc_formulation_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('planning_of_ndc_formulation_details', models.CharField(default='NA', max_length=125)),
                ('stakeholder_consultation_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('stakeholder_consultation_details', models.CharField(default='NA', max_length=125)),
                ('education_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('education_details', models.CharField(default='NA', max_length=125)),
                ('aw_rais_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('aw_rais_details', models.CharField(default='NA', max_length=125)),
                ('training_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('training_details', models.CharField(default='NA', max_length=125)),
                ('info_access_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('info_access_details', models.CharField(default='NA', max_length=125)),
                ('planning_of_ndc_implementation_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('planning_of_ndc_implementation_details', models.CharField(default='NA', max_length=125)),
                ('monitoring_and_review_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('monitoring_and_review_details', models.CharField(default='NA', max_length=125)),
                ('sustainable_development_goals_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('sustainable_development_goals_details', models.CharField(default='NA', max_length=125)),
                ('sustainable_development_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('sustainable_development_details', models.CharField(default='NA', max_length=125)),
                ('fossil_fuel_subsidy_reform_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('fossil_fuel_subsidy_reform_details', models.CharField(default='NA', max_length=125)),
                ('green_economy_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('green_economy_details', models.CharField(default='NA', max_length=125)),
                ('disaster_risk_reduction_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('disaster_risk_reduction_details', models.CharField(default='NA', max_length=125)),
                ('section_on_fairness_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('section_on_fairness_details', models.CharField(default='NA', max_length=125)),
                ('historical_responsibility_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('historical_responsibility_details', models.CharField(default='NA', max_length=125)),
                ('loss_and_damage_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('loss_and_damage_details', models.CharField(default='NA', max_length=125)),
                ('gender_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('gender_details', models.CharField(default='NA', max_length=125)),
                ('human_rights_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('human_rights_details', models.CharField(default='NA', max_length=125)),
                ('income_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('income_details', models.CharField(default='NA', max_length=125)),
                ('region_id', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('region_name', models.CharField(default='NA', max_length=125)),
                ('g20_class', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NA', max_length=75)),
                ('g20_details', models.CharField(default='NA', max_length=125)),
            ],
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='adaptation_documents_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='adaptation_documents_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='agriculture_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='agriculture_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='aw_rais_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='aw_rais_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='carbon_capture_and_storage_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='carbon_capture_and_storage_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='climate_risk_insurance_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='climate_risk_insurance_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='climate_risks_droughts_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='climate_risks_droughts_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='climate_risks_extreme_weather_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='climate_risks_extreme_weather_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='climate_risks_floods_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='climate_risks_floods_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='climate_risks_sea_level_rise_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='climate_risks_sea_level_rise_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='climate_risks_temp_increase_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='climate_risks_temp_increase_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='co_benefits_ccm_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='co_benefits_ccm_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='co_benefits_of_adaptation_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='co_benefits_of_adaptation_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='conditionality_of_adaptation_finance_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='conditionality_of_adaptation_finance_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='conditionality_of_capacity_building_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='conditionality_of_capacity_building_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='conditionality_of_mitigation_finance_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='conditionality_of_mitigation_finance_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='conditionality_of_technology_transfer_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='conditionality_of_technology_transfer_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='costs_of_adaptation_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='costs_of_adaptation_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='costs_of_ccm_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='costs_of_ccm_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='costs_of_future_climate_related_hazards_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='costs_of_future_climate_related_hazards_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='costs_of_recent_climate_related_hazards_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='costs_of_recent_climate_related_hazards_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='disaster_risk_reduction_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='disaster_risk_reduction_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='education_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='education_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='energy_efficiency_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='energy_efficiency_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='fossil_fuel_production_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='fossil_fuel_production_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='fossil_fuel_subsidiaries_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='fossil_fuel_subsidiaries_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='fossil_fuel_subsidy_reform_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='fossil_fuel_subsidy_reform_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='g20_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='g20_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='gender_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='gender_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='green_economy_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='green_economy_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='historical_responsibility_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='historical_responsibility_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='human_rights_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='human_rights_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='income_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='income_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='info_access_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='info_access_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='land_use_and_forestry_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='land_use_and_forestry_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='land_use_change_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='land_use_change_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='loss_and_damage_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='loss_and_damage_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='market_mechanisms_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='market_mechanisms_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='means_of_implementation_and_fairness_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='means_of_implementation_and_fairness_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='migration_and_displacement_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='migration_and_displacement_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='mitigation_documents_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='mitigation_documents_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='monitoring_and_review_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='monitoring_and_review_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='planning_of_ndc_formulation_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='planning_of_ndc_formulation_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='planning_of_ndc_implementation_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='planning_of_ndc_implementation_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='priority_sectors_agriculture_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='priority_sectors_agriculture_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='priority_sectors_ecosystems_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='priority_sectors_ecosystems_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='priority_sectors_forestry_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='priority_sectors_forestry_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='priority_sectors_health_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='priority_sectors_health_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='priority_sectors_water_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='priority_sectors_water_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='quantified_adaptation_targets_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='quantified_adaptation_targets_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='redd_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='redd_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='reducing_non_co2_gases_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='reducing_non_co2_gases_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='renewable_energy_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='renewable_energy_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='section_on_fairness_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='section_on_fairness_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='stakeholder_consultation_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='stakeholder_consultation_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='sustainable_development_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='sustainable_development_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='sustainable_development_goals_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='sustainable_development_goals_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='technology_needs_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='technology_needs_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='temp_target_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='temp_target_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='trade_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='trade_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='training_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='training_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='transport_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='transport_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='type_of_target_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='type_of_target_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='vulnerability_agriculture_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='vulnerability_agriculture_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='vulnerability_coastal_zones_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='vulnerability_coastal_zones_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='vulnerability_ecosystems_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='vulnerability_ecosystems_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='vulnerability_health_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='vulnerability_health_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='vulnerability_water_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='vulnerability_water_details',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='waste_class',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='waste_details',
        ),
    ]
