# Generated by Django 3.1.3 on 2020-11-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201119_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ndc',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='NDC_Text',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='Submission_date',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='Submission_type',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='country',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='ref_num',
        ),
        migrations.RemoveField(
            model_name='ndc',
            name='title',
        ),
    ]
