# Generated by Django 3.1.3 on 2020-11-28 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20201128_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndc',
            name='Submission_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
