# Generated by Django 3.1.3 on 2020-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_ndc_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndc',
            name='Description',
            field=models.TextField(default='NA', max_length=250),
        ),
        migrations.AddField(
            model_name='ndc',
            name='NDC_Text',
            field=models.FileField(default='NA', max_length=254, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='ndc',
            name='Submission_type',
            field=models.CharField(choices=[('base year emissions goal', 'BASE YEAR EMISSIONS GOAL'), ('fixed-level goal', 'FIXED-LEVEL GOAL'), ('base year intensity goal', 'BASE YEAR INTENSITY GOAL'), ('baseline emissions goal', 'BASELINE EMISSIONS GOAL')], default='base year emissions goal', max_length=75),
        ),
        migrations.AddField(
            model_name='ndc',
            name='ref_num',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='ndc',
            name='title',
            field=models.CharField(default='NDC', max_length=100),
        ),
    ]
