# Generated by Django 3.1.3 on 2021-01-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210121_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndc',
            name='IPFS_CID',
            field=models.CharField(default='IPFS CID', max_length=100),
        ),
    ]
