CREATE TABLE `ndc_data_testing` (
  `adaptation_documents_class` tinyint(3) unsigned NOT NULL,
  `adaptation_documents_details` text NOT NULL,
  `agriculture_class` tinyint(3) unsigned NOT NULL,
  `agriculture_details` varchar(125) NOT NULL,
  `aw_rais_class` tinyint(3) unsigned NOT NULL,
  `aw_rais_details` varchar(125) NOT NULL,
  `carbon_capture_and_storage_class` tinyint(3) unsigned NOT NULL,
  `carbon_capture_and_storage_details` varchar(125) NOT NULL,
  `climate_risk_insurance_class` tinyint(3) unsigned NOT NULL,
  `climate_risk_insurance_details` varchar(125) NOT NULL,
  `climate_risks_droughts_class` tinyint(3) unsigned NOT NULL,
  `climate_risks_droughts_details` varchar(125) NOT NULL,
  `climate_risks_extreme_weather_class` tinyint(3) unsigned NOT NULL,
  `climate_risks_extreme_weather_details` varchar(125) NOT NULL,
  `climate_risks_floods_class` tinyint(3) unsigned NOT NULL,
  `climate_risks_floods_details` varchar(125) NOT NULL,
  `climate_risks_sea_level_rise_class` tinyint(3) unsigned NOT NULL,
  `climate_risks_sea_level_rise_details` varchar(125) NOT NULL,
  `climate_risks_temp_increase_class` tinyint(3) unsigned NOT NULL,
  `climate_risks_temp_increase_details` varchar(125) NOT NULL,
  `co_benefits_ccm_class` tinyint(3) unsigned NOT NULL,
  `co_benefits_ccm_details` varchar(255) NOT NULL,
  `co_benefits_of_adaptation_class` tinyint(3) unsigned NOT NULL,
  `co_benefits_of_adaptation_details` varchar(255) NOT NULL,
  `conditionality_of_adaptation_finance_class` tinyint(3) unsigned NOT NULL,
  `conditionality_of_adaptation_finance_details` varchar(125) NOT NULL,
  `conditionality_of_capacity_building_class` tinyint(3) unsigned NOT NULL,
  `conditionality_of_capacity_building_details` varchar(125) NOT NULL,
  `conditionality_of_mitigation_finance_class` tinyint(3) unsigned NOT NULL,
  `conditionality_of_mitigation_finance_details` varchar(125) NOT NULL,
  `conditionality_of_technology_transfer_class` tinyint(3) unsigned NOT NULL,
  `conditionality_of_technology_transfer_details` varchar(125) NOT NULL,
  `costs_of_adaptation_class` tinyint(3) unsigned NOT NULL,
  `costs_of_adaptation_details` varchar(125) NOT NULL,
  `costs_of_ccm_class` tinyint(3) unsigned NOT NULL,
  `costs_of_ccm_details` varchar(125) NOT NULL,
  `costs_of_future_climate_related_hazards_class` tinyint(3) unsigned NOT NULL,
  `costs_of_future_climate_related_hazards_details` varchar(255) NOT NULL,
  `costs_of_recent_climate_related_hazards_class` tinyint(3) unsigned NOT NULL,
  `costs_of_recent_climate_related_hazards_details` varchar(255) NOT NULL,
  `country_code` char(3) NOT NULL,
  `country_name` varchar(75) NOT NULL,
  `disaster_risk_reduction_class` tinyint(3) unsigned NOT NULL,
  `disaster_risk_reduction_details` varchar(125) NOT NULL,
  `education_class` tinyint(3) unsigned NOT NULL,
  `education_details` varchar(125) NOT NULL,
  `energy_efficiency_class` tinyint(3) unsigned NOT NULL,
  `energy_efficiency_details` varchar(255) NOT NULL,
  `fossil_fuel_production_class` tinyint(3) unsigned NOT NULL,
  `fossil_fuel_production_details` varchar(255) NOT NULL,
  `fossil_fuel_subsidiaries_class` tinyint(3) unsigned NOT NULL,
  `fossil_fuel_subsidiaries_details` varchar(125) NOT NULL,
  `fossil_fuel_subsidy_reform_class` tinyint(3) unsigned NOT NULL,
  `fossil_fuel_subsidy_reform_details` varchar(125) NOT NULL,
  `g20_class` tinyint(3) unsigned NOT NULL,
  `g20_details` varchar(125) NOT NULL,
  `gender_class` tinyint(3) unsigned NOT NULL,
  `gender_details` varchar(125) NOT NULL,
  `green_economy_class` tinyint(3) unsigned NOT NULL,
  `green_economy_details` varchar(125) NOT NULL,
  `historical_responsibility_class` tinyint(3) unsigned NOT NULL,
  `historical_responsibility_details` varchar(125) NOT NULL,
  `human_rights_class` tinyint(3) unsigned NOT NULL,
  `human_rights_details` varchar(125) NOT NULL,
  `income_class` tinyint(3) unsigned NOT NULL,
  `income_details` varchar(125) NOT NULL,
  `info_access_class` tinyint(3) unsigned NOT NULL,
  `info_access_details` varchar(125) NOT NULL,
  `land_use_and_forestry_class` tinyint(3) unsigned NOT NULL,
  `land_use_and_forestry_details` varchar(255) NOT NULL,
  `land_use_change_class` tinyint(3) unsigned NOT NULL,
  `land_use_change_details` varchar(125) NOT NULL,
  `loss_and_damage_class` tinyint(3) unsigned NOT NULL,
  `loss_and_damage_details` varchar(125) NOT NULL,
  `market_mechanisms_class` tinyint(3) unsigned NOT NULL,
  `market_mechanisms_details` varchar(125) NOT NULL,
  `means_of_implementation_and_fairness_class` tinyint(3) unsigned NOT NULL,
  `means_of_implementation_and_fairness_details` varchar(125) NOT NULL,
  `migration_and_displacement_class` tinyint(3) unsigned NOT NULL,
  `migration_and_displacement_details` varchar(255) NOT NULL,
  `mitigation_documents_class` tinyint(3) unsigned NOT NULL,
  `mitigation_documents_details` text NOT NULL,
  `monitoring_and_review_class` tinyint(3) unsigned NOT NULL,
  `monitoring_and_review_details` varchar(125) NOT NULL,
  `planning_of_ndc_formulation_class` tinyint(3) unsigned NOT NULL,
  `planning_of_ndc_formulation_details` varchar(125) NOT NULL,
  `planning_of_ndc_implementation_class` tinyint(3) unsigned NOT NULL,
  `planning_of_ndc_implementation_details` varchar(125) NOT NULL,
  `priority_sectors_agriculture_class` tinyint(3) unsigned NOT NULL,
  `priority_sectors_agriculture_details` varchar(125) NOT NULL,
  `priority_sectors_ecosystems_class` tinyint(3) unsigned NOT NULL,
  `priority_sectors_ecosystems_details` varchar(125) NOT NULL,
  `priority_sectors_forestry_class` tinyint(3) unsigned NOT NULL,
  `priority_sectors_forestry_details` varchar(125) NOT NULL,
  `priority_sectors_health_class` tinyint(3) unsigned NOT NULL,
  `priority_sectors_health_details` varchar(125) NOT NULL,
  `priority_sectors_water_class` tinyint(3) unsigned NOT NULL,
  `priority_sectors_water_details` varchar(125) NOT NULL,
  `quantified_adaptation_targets_class` tinyint(3) unsigned NOT NULL,
  `quantified_adaptation_targets_details` varchar(125) NOT NULL,
  `redd_class` tinyint(3) unsigned NOT NULL,
  `redd_details` varchar(255) NOT NULL,
  `reducing_non_co2_gases_class` tinyint(3) unsigned NOT NULL,
  `reducing_non_co2_gases_details` varchar(125) NOT NULL,
  `region_id` varchar(75) NOT NULL,
  `region_name` varchar(125) NOT NULL,
  `renewable_energy_class` tinyint(3) unsigned NOT NULL,
  `renewable_energy_details` varchar(255) NOT NULL,
  `section_on_fairness_class` tinyint(3) unsigned NOT NULL,
  `section_on_fairness_details` varchar(125) NOT NULL,
  `stakeholder_consultation_class` tinyint(3) unsigned NOT NULL,
  `stakeholder_consultation_details` varchar(255) NOT NULL,
  `sustainable_development_class` tinyint(3) unsigned NOT NULL,
  `sustainable_development_details` varchar(255) NOT NULL,
  `sustainable_development_goals_class` tinyint(3) unsigned NOT NULL,
  `sustainable_development_goals_details` varchar(125) NOT NULL,
  `technology_needs_class` tinyint(3) unsigned NOT NULL,
  `technology_needs_details` varchar(125) NOT NULL,
  `temp_target_class` tinyint(3) unsigned NOT NULL,
  `temp_target_details` varchar(125) NOT NULL,
  `trade_class` tinyint(3) unsigned NOT NULL,
  `trade_details` varchar(255) NOT NULL,
  `training_class` tinyint(3) unsigned NOT NULL,
  `training_details` varchar(125) NOT NULL,
  `transport_class` tinyint(3) unsigned NOT NULL,
  `transport_details` varchar(255) NOT NULL,
  `type_of_target_class` tinyint(3) unsigned NOT NULL,
  `type_of_target_details` varchar(125) NOT NULL,
  `vulnerability_agriculture_class` tinyint(3) unsigned NOT NULL,
  `vulnerability_agriculture_details` varchar(125) NOT NULL,
  `vulnerability_coastal_zones_class` tinyint(3) unsigned NOT NULL,
  `vulnerability_coastal_zones_details` varchar(125) NOT NULL,
  `vulnerability_ecosystems_class` tinyint(3) unsigned NOT NULL,
  `vulnerability_ecosystems_details` varchar(125) NOT NULL,
  `vulnerability_health_class` tinyint(3) unsigned NOT NULL,
  `vulnerability_health_details` varchar(125) NOT NULL,
  `vulnerability_water_class` tinyint(3) unsigned NOT NULL,
  `vulnerability_water_details` varchar(125) NOT NULL,
  `waste_class` tinyint(3) unsigned NOT NULL,
  `waste_details` varchar(125) NOT NULL,
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `author_id` int(11) NOT NULL,
  `slug` varchar(50) NOT NULL DEFAULT '',
  `Submission_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Description` longtext NOT NULL,
  `NDC_Text` varchar(255) NOT NULL DEFAULT '',
  `Submission_type` varchar(75) NOT NULL DEFAULT '',
  `ref_num` int(11) NOT NULL,
  `title` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=170 DEFAULT CHARSET=utf8;
